# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Category', max_length=225)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CorrectChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=225)),
                ('negative', models.BooleanField()),
                ('marks', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Exam_portal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Exam_portal.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_no', models.IntegerField()),
                ('branch', models.CharField(max_length=5)),
                ('contact', models.BigIntegerField()),
                ('skills', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('hosteler', models.BooleanField()),
                ('designer', models.CharField(max_length=10, verbose_name='Mention any software you worked on(photoshop etc)')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.Field(max_length=225)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('time', models.TimeField(null=True)),
                ('questions', models.ManyToManyField(related_name='tests', to='Exam_portal.Question')),
            ],
        ),
        migrations.AddField(
            model_name='correctchoice',
            name='correct_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.QuestionChoice'),
        ),
        migrations.AddField(
            model_name='correctchoice',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='correctchoice',
            unique_together=set([('question', 'correct_choice')]),
        ),
    ]
