# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0002_auto_20160228_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='choice',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
