# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0005_auto_20160406_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksOfStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.Student')),
            ],
        ),
    ]
