# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0006_marksofstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.IntegerField(null=True),
        ),
    ]
