# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0007_question_negative_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exam_portal.QuestionChoice'),
        ),
    ]
