# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0008_auto_20160410_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
    ]
