# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0009_remove_test_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
