# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0011_auto_20160414_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
